<?php

declare(strict_types=1);

namespace Tests\Unit\Libraries\Currency;

use App\Libraries\Currency\CurrencyBackoff;
use PHPUnit\Framework\TestCase;
use STS\Backoff\Backoff;
use Mockery as m;

class CurrencyBackoffUnitTest  extends TestCase
{
    /**
     * @var CurrencyBackoff
     */
    private $currencyBackoff;

    public function setUp(): void
    {
        $this->currencyBackoff = new CurrencyBackoff();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @group unit
     * @return void
     */
    public function it_should_return_instance()
    {
        $this->assertInstanceOf(Backoff::class, $this->currencyBackoff->instance());
    }
}
